name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'production'
env:
  REGION: ${{ vars.REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
