name: Build And Push to Docker Hub

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'production'

env:
  DOCKER_HUB_REPOSITORY: abbass69/github-actions  # 👈 Change this

permissions:
  contents: read

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # 👈 Docker Hub username
          password: ${{ secrets.DOCKER_HUB_TOKEN }}     # 👈 Docker Hub PAT (Personal Access Token)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:latest -t $DOCKER_HUB_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_HUB_REPOSITORY:latest
          docker push $DOCKER_HUB_REPOSITORY:$IMAGE_TAG
          echo "image=$DOCKER_HUB_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Image digest
        run: echo ${{ steps.build-image.outputs.digest }}
